In [1]:
### get log_session
# update file path

# with open ('/Users/baselhussein/eyegaze/34_4.txt', "r") as log: 
#     log_session = log.readline()

In [2]:
# # get date and time

# log_session_datetime = log_session
# log_session_datetime

'ID,Global timestamp,Timestamp,Event type,Event,Level,Details\n'

In [40]:
# log_date = log_session_datetime[16:26]
# log_date

'06/01/2022'

In [46]:
# log_time = log_session_datetime[27:35]
# log_time

'09:51:12'

In [17]:
### read file

In [3]:
# log_file = open("/Users/baselhussein/eyegaze/38_0.txt", "r")

# lines = log_file.readlines()

In [4]:
#a_file.close()

In [5]:
# lines

['ID,Global timestamp,Timestamp,Event type,Event,Level,Details\n',
 '34,0:0:11.05:5,0:0:0:0,event,start,0level,\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,text_baba:12:7\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,wall:12:9\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,tile:12:10\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,tile:12:11\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,tile:12:12\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,wall:12:13\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,text_wall:12:15\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,text_is:13:7\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,wall:13:9\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,tile:13:10\n',
 '34,0:0:11.05:5,0:0:0:0,event,init_object,0level:baba is you,baba:13:11\n',
 '34,0:0:11.05:5,0:0:0:0,eve

In [9]:
### write new text file 

In [31]:
# log_new = open("/Users/baselhussein/eyegaze/34_4.txt", "w")

# for line in lines:
#     if line.strip("\n") != "Session started 06/01/2022 09:51:12": 
#         log_new.write(line)

In [32]:
### must close file 
# log_new.close()

In [2]:
### read into Pandas

import pandas as pd

In [3]:
log_data = pd.read_csv("/Users/baselhussein/eyegaze/38_0.txt")

In [4]:
log_data


ID  Global timestamp        Timestamp Event type        Event  \
0      38       0:0:40.7:70          0:0:0:0      event        start   
1      38       0:0:40.7:70          0:0:0:0      event  init_object   
2      38       0:0:40.7:70          0:0:0:0      event  init_object   
3      38       0:0:40.7:70          0:0:0:0      event  init_object   
4      38       0:0:40.7:70          0:0:0:0      event  init_object   
...    ..               ...              ...        ...          ...   
27819  38      0:35:30.4:40   0:0:8.73333:73      input        right   
27820  38     0:35:30.55:55   0:0:8.88333:88      input        right   
27821  38  0:35:31.63333:63   0:0:9.96667:96     change    mapcursor   
27822  38  0:35:31.63333:63   0:0:9.96667:96      input         down   
27823  38  0:35:33.33333:33  0:0:11.66667:66      input          end   

                                 Level    Details  
0                             101level        NaN  
1      101level:Welcome to the museum!  grass:1:1  
2      101level:Welcome to the museum!  grass:1:2  
3      101level:Welcome to the museum!  grass:1:3  
4      101level:Welcome to the museum!  grass:1:4  
...                                ...        ...  
27819      207level:2. solitary island        NaN  
27820      207level:2. solitary island        NaN  
27821      207level:2. solitary island    7:3:173  
27822      207level:2. solitary island        NaN  
27823      207level:2. solitary island        NaN  

[27824 rows x 7 columns]

In [57]:
#log_data["log_date"] = log_date

In [58]:
#log_data["log_time"] = log_time

In [5]:
#pd.set_option('display.max_rows', None)
log_data

ID  Global timestamp        Timestamp Event type        Event  \
0      38       0:0:40.7:70          0:0:0:0      event        start   
1      38       0:0:40.7:70          0:0:0:0      event  init_object   
2      38       0:0:40.7:70          0:0:0:0      event  init_object   
3      38       0:0:40.7:70          0:0:0:0      event  init_object   
4      38       0:0:40.7:70          0:0:0:0      event  init_object   
...    ..               ...              ...        ...          ...   
27819  38      0:35:30.4:40   0:0:8.73333:73      input        right   
27820  38     0:35:30.55:55   0:0:8.88333:88      input        right   
27821  38  0:35:31.63333:63   0:0:9.96667:96     change    mapcursor   
27822  38  0:35:31.63333:63   0:0:9.96667:96      input         down   
27823  38  0:35:33.33333:33  0:0:11.66667:66      input          end   

                                 Level    Details  
0                             101level        NaN  
1      101level:Welcome to the museum!  grass:1:1  
2      101level:Welcome to the museum!  grass:1:2  
3      101level:Welcome to the museum!  grass:1:3  
4      101level:Welcome to the museum!  grass:1:4  
...                                ...        ...  
27819      207level:2. solitary island        NaN  
27820      207level:2. solitary island        NaN  
27821      207level:2. solitary island    7:3:173  
27822      207level:2. solitary island        NaN  
27823      207level:2. solitary island        NaN  

[27824 rows x 7 columns]

In [6]:
### split string after colon 

details_split = log_data["Details"].str.split(":", n = 4, expand = True)

In [7]:
details_split 

0    1    2     3
0        NaN  NaN  NaN   NaN
1      grass    1    1  None
2      grass    1    2  None
3      grass    1    3  None
4      grass    1    4  None
...      ...  ...  ...   ...
27819    NaN  NaN  NaN   NaN
27820    NaN  NaN  NaN   NaN
27821      7    3  173  None
27822    NaN  NaN  NaN   NaN
27823    NaN  NaN  NaN   NaN

[27824 rows x 4 columns]

In [8]:
### add coordinates to df

log_data['object'] = details_split[0]
log_data['xCoordinate'] = details_split[1]
log_data['yCoordinate'] = details_split[2]
log_data['zCoordinateOrRuleActive'] = details_split[3]

In [45]:
log_data.head(100)

ID Global timestamp Timestamp Event type        Event  \
0   38      0:0:40.7:70   0:0:0:0      event        start   
1   38      0:0:40.7:70   0:0:0:0      event  init_object   
2   38      0:0:40.7:70   0:0:0:0      event  init_object   
3   38      0:0:40.7:70   0:0:0:0      event  init_object   
4   38      0:0:40.7:70   0:0:0:0      event  init_object   
..  ..              ...       ...        ...          ...   
95  38      0:0:40.7:70   0:0:0:0      event  init_object   
96  38      0:0:40.7:70   0:0:0:0      event  init_object   
97  38      0:0:40.7:70   0:0:0:0      event  init_object   
98  38      0:0:40.7:70   0:0:0:0      event  init_object   
99  38      0:0:40.7:70   0:0:0:0      event  init_object   

                              Level       Details   object xCoordinate  \
0                          101level           NaN      NaN         NaN   
1   101level:Welcome to the museum!     grass:1:1    grass           1   
2   101level:Welcome to the museum!     grass:1:2    grass           1   
3   101level:Welcome to the museum!     grass:1:3    grass           1   
4   101level:Welcome to the museum!     grass:1:4    grass           1   
..                              ...           ...      ...         ...   
95  101level:Welcome to the museum!  foliage:14:3  foliage          14   
96  101level:Welcome to the museum!    brick:14:9    brick          14   
97  101level:Welcome to the museum!   brick:14:10    brick          14   
98  101level:Welcome to the museum!   brick:14:11    brick          14   
99  101level:Welcome to the museum!   grass:14:17    grass          14   

   yCoordinate zCoordinateOrRuleActive interestArea  
0          NaN                     NaN    RECTANGLE  
1            1                    None    RECTANGLE  
2            2                    None    RECTANGLE  
3            3                    None    RECTANGLE  
4            4                    None    RECTANGLE  
..         ...                     ...          ...  
95           3                    None    RECTANGLE  
96           9                    None    RECTANGLE  
97          10                    None    RECTANGLE  
98          11                    None    RECTANGLE  
99          17                    None    RECTANGLE  

[100 rows x 12 columns]

In [51]:
log_data.xCoordinate.unique()

array([nan, '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '0'],
      dtype=object)

In [52]:
log_data.object.unique()

array([nan, 'grass', 'brick', 'pillar', 'baba', 'flower', 'fungi', 'key',
       'foliage', 'wall', 'door', 'text_door', 'sign', 'statue',
       'text_wall', 'text_is', 'text_shut', 'text_stop', 'text_key',
       'text_push', 'text_and', 'text_open', 'text_flag', 'text_baba',
       'flag', 'text_win', 'text_you', '21', '25', '31', 'fence', 'fruit',
       'hedge', 'fungus', 'tree', 'rose', 'level', 'cursor', 'line', '12',
       '11', '10', '9', '8', '7', '6', 'box', 'star', 'love', '5', 'tile',
       'rock', 'text_rock', '20', '16', '15', '14', '13', 'water',
       'text_water', 'text_sink', '1', '2', 'skull', 'text_skull',
       'text_defeat', '3', 'lava', 'text_lava', 'text_melt', 'text_hot',
       '26', 'text_grass', '24', 'algae', 'crab', 'jelly', 'ice',
       'text_jelly', 'text_crab', 'text_star', '22', 'text_algae',
       'text_love', 'keke', 'text_keke', 'text_move', 'text_pillar', '4',
       'bubble', '19', '17', 'text_hedge', 'pipe', 'robot', 'cog',
       'violet'

In [50]:
log_data.zCoordinateOrRuleActive.unique()

array([nan, None, '0', '3', '2', '1'], dtype=object)

In [44]:
log_data.yCoordinate.unique()

array([nan, '1', '2', '3', '4', '8', '9', '10', '16', '17', '18', '6',
       '11', '13', '7', '12', '15', '5', '14', 'door is shut ',
       'wall is stop ', 'door is stop ', 'key is push and open ',
       'flag is win ', 'baba is you ', '172', '52', 'rock is push ',
       'wall is you ', 'flag is stop ', 'wall is win ', 'water is sink ',
       'rock is win ', 'skull is defeat ', 'baba is melt ',
       'lava is hot ', 'lava is push ', 'rock is stop ', 'grass is stop ',
       '142', 'baba is you and sink ', 'jelly is sink ',
       'baba is you and wall ', 'wall and baba is you ', 'star is sink ',
       'star is sink and push ', 'crab and baba is you ',
       'algae is defeat ', 'love is win ', 'keke is move ',
       'love is push ', 'keke is push ', 'pillar is push ',
       'star is defeat ', 'pillar is you ', 'baba is win ',
       'flag is defeat ', 'crab is defeat ', 'rock is you ',
       'jelly is push ', 'key is open ', 'key is push ', 'rock is open ',
       'door is o

In [16]:
### drop columns for eye-tracker
log_data.drop(columns=['ID', 'Global timestamp', "Event type", "Event", "Level"])

Timestamp    Details object xCoordinate yCoordinate  \
0              0:0:0:0        NaN    NaN         NaN         NaN   
1              0:0:0:0  grass:1:1  grass           1           1   
2              0:0:0:0  grass:1:2  grass           1           2   
3              0:0:0:0  grass:1:3  grass           1           3   
4              0:0:0:0  grass:1:4  grass           1           4   
...                ...        ...    ...         ...         ...   
27819   0:0:8.73333:73        NaN    NaN         NaN         NaN   
27820   0:0:8.88333:88        NaN    NaN         NaN         NaN   
27821   0:0:9.96667:96    7:3:173      7           3         173   
27822   0:0:9.96667:96        NaN    NaN         NaN         NaN   
27823  0:0:11.66667:66        NaN    NaN         NaN         NaN   

      zCoordinateOrRuleActive interestArea  
0                         NaN    RECTANGLE  
1                        None    RECTANGLE  
2                        None    RECTANGLE  
3                        None    RECTANGLE  
4                        None    RECTANGLE  
...                       ...          ...  
27819                     NaN    RECTANGLE  
27820                     NaN    RECTANGLE  
27821                    None    RECTANGLE  
27822                     NaN    RECTANGLE  
27823                     NaN    RECTANGLE  

[27824 rows x 7 columns]

In [17]:
### add interest area column

log_data['interestArea'] = 'RECTANGLE'

In [43]:
date_time = log_data['Timestamp']

date_time

0                0:0:0:0
1                0:0:0:0
2                0:0:0:0
3                0:0:0:0
4                0:0:0:0
              ...       
27819     0:0:8.73333:73
27820     0:0:8.88333:88
27821     0:0:9.96667:96
27822     0:0:9.96667:96
27823    0:0:11.66667:66
Name: Timestamp, Length: 27824, dtype: object

In [53]:
#s = pd.Series(pd.to_timedelta(np.arange(5), unit='d'))

In [24]:
from datetime import datetime

In [40]:
new_time = datetime.strptime(timestamps_list, "%H:%M:%S:%MS")

TypeError: strptime() argument 1 must be str, not list

In [54]:
### export 
log_data.to_csv('test.csv', header=False, index=False)